### PR TITLE
Add a class when .drag hovers a .drop

### PR DESCRIPTION
**Pull request by athieriot**
Hi !

   Thank you for last time improvement. And I know it's been a while since then but at the end I needed something else to make it work like I wanted.

   This configuration works nicely for me when a drag element hovers a drop element.

   I thing there is all the different possibilities now :)

Thank you

### CODE REVIEW

**Comment by fisshy** [comment]
Hi!

Thanks for your PR.

So basically what this do is that it adds a class to the dropable area when you hover it with your dragable item.

The dragover event triggers every time you move your mouse position, I'm not sure if $element.addClass() will cause any performance issues if triggered 100times/s since the DOM is cached in the directive. But I solved that with adding a flag "hasHover" for the dragable item ( see the events for drag directive )

**Comment by athieriot** [comment]
This seems fair.

I modified my code by adding the same kind of boolean you used for the draggable elements.

Hope this help.

**Comment by fisshy** [comment]
Awesome! merged!

**Comment by athieriot** [comment]
Sweet !
Thank you.

Oh I've just noticed I forgot to update the bower.json file :/

**Pull request merged**
