### PR TITLE
Better MCV pattern

### PR DESCRIPTION
**Pull request by floribon**
This solve a bug when classes are added with jQuery after you manually concatened one using className property. 

It also improve separation between model and view.

As an extra, I added the targeted element to the when-drop function, but I may be missing something. For instance, why do you bind "drop" from the drop directive? Seems like its value ($scope.drop) is never used.

---
- "on-drag" class added or removed instead of hard-coded opacity for
  elements being dragged (opacity moved to css file)
- jQ-lite addClass and removeClass instead of pure js string
  concatenation (makes jQuery addClass break)
- when-drop function returns the target element as a second optional
  parameter

### CODE REVIEW

**Comment by fisshy** [comment]
If you want to access the target element you have to write

I'm pretty sure you have to be specific like this
 whendrop="myFunc(data, target)"

I'm not 100% sure what you mean with
"For instance, why do you bind "drop" from the drop directive? Seems like its value ($scope.drop) is never used."

**Comment by floribon** [comment]
Sorry I'm not sure to get the first part of your message. With that commit you can write whendrop="myFunc(data, target)", otherwise only one param "data" is available thus we don't know on which element we are dropping things.

The second part is not important, I was just wondering why you bind a value on scope.drop (by writing drop: '=' in the isolate scope definition) when you never use it in the directive.

PS: Also, I'm not used to pull-requesting stuff so feel free not to merge it, that's also why I wrongly edited the README file (I thought it would be updated on my forked repo only)

**Comment by fisshy** [comment]
Exactly,
if you want to send parameters back to whenDrop
You have to specify the parameters in the html-directive
whemDrop("myFunc(data, target)");
I'm pretty sure the names has to match tho, You can try it.
/J

Date: Fri, 16 Aug 2013 00:05:31 -0700

**Comment by floribon** [comment]
Well, I tried it and it doen't work :/ I don't want to insist but currently when-drop will only return the content of dndApi.getData() which is the data being dropped, not the DOM target element. My changes allow that behavior (with a strict name matching).

**Comment by fisshy** [comment]
Yes currently, but with your changes it should work :)
Haven't been able to test it yet ( at work )
But will do when I get time over and then I'll merge it.
/J

Date: Fri, 16 Aug 2013 00:30:26 -0700

**Pull request merged**
